/*--------------------------------------------------TABLA PERSONAL  ---------------------------------------------------------------*/
CREATE TABLE PERSONAL (
    CEDULA_PERSONAL INT NOT NULL,
    NOMBRE_PERSONAL VARCHAR(100) NOT NULL DEFAULT 'NOMBRE',
    APELLIDO_PERSONAL VARCHAR(100) NOT NULL DEFAULT 'APELLIDO',
    FECHA_NACIMIENTO DATE NOT NULL,
    EDAD_PERSONAL INT NOT NULL,
    TELEFONO_PERSONAL INT NOT NULL,
    CORREO_PERSONAL VARCHAR(100) NOT NULL,
    DIRECCION TEXT NOT NULL,
    CLAVE VARCHAR(100) NOT NULL DEFAULT 'FISHIO2024PERSONAL',
    ROL VARCHAR(50) DEFAULT 'PERSONAL',
    PRIMARY KEY (CEDULA_PERSONAL),
    CONSTRAINT UK_TELEFONO UNIQUE (TELEFONO_PERSONAL),
    CONSTRAINT UK_CORREO UNIQUE (CORREO_PERSONAL)
);

/*--------------------------------------------------PC CREAR PERSONAL  ---------------------------------------------------------------*/
DROP PROCEDURE SP_CREAR_PERSONAL;
DELIMITER //
CREATE PROCEDURE SP_CREAR_PERSONAL (
IN TCEDULA_PERSONAL INT, 
IN TNOMBRE_PERSONAL VARCHAR(100), 
IN TAPELLIDO_PERSONAL VARCHAR(100),
IN TFECHA_NACIMIENTO DATE, 
IN TEDAD_PERSONAL INT, 
IN TTELEFONO_PERSONAL INT, 
IN TCORREO_PERSONAL VARCHAR(100), 
IN TDIRECCION TEXT,
IN TCLAVE VARCHAR(100)
)
BEGIN 
DECLARE MSJ VARCHAR(50);
START TRANSACTION;
/*VALIDAMOS LA CLAVE PARA QUE NO ACEPTE INFORMACIÓN NULA*/
	IF LENGTH(TCLAVE) <= 0 THEN
		SET MSJ = ("LA CLAVE DEBE TENER AL MENOS UN CARACTER");
		SELECT MSJ;
        ROLLBACK;
	ELSE 
		INSERT INTO PERSONAL
		(CEDULA_PERSONAL, NOMBRE_PERSONAL, APELLIDO_PERSONAL, FECHA_NACIMIENTO, EDAD_PERSONAL, TELEFONO_PERSONAL, CORREO_PERSONAL, DIRECCION, CLAVE)
		VALUES (TRIM(TCEDULA_PERSONAL), 
				TRIM(TNOMBRE_PERSONAL), 
                TRIM(TAPELLIDO_PERSONAL), 
                TRIM(TFECHA_NACIMIENTO), 
                TRIM(TEDAD_PERSONAL), 
                TRIM(TTELEFONO_PERSONAL), 
                TRIM(TCORREO_PERSONAL), 
                TRIM(TDIRECCION), 
                TRIM(TCLAVE));
		COMMIT;
	END IF;
END //
DELIMITER ;
CALL SP_CREAR_PERSONAL
(1312559825, "Rosa", "Valarezo", "1996-01-08",timestampdiff(YEAR , '1996-08-01', NOW()), 
0979853522, "mia@gmail.com", "Los Esteros","Mia");
/*--------------------------------------------FUNCION PARA OBTENER CEDULA PERSONAL -------------------------------------------------*/
DROP FUNCTION F_CEDULA_PERSONAL_F;
DELIMITER //
CREATE FUNCTION F_CEDULA_PERSONAL_F(TCEDULA_PERSONAL INT)
RETURNS INT DETERMINISTIC 
BEGIN
    RETURN (SELECT CEDULA_PERSONAL FROM PERSONAL WHERE CEDULA_PERSONAL =  TCEDULA_PERSONAL);
END //
DELIMITER ;
SELECT F_CEDULA_PERSONAL_F(1312559825);
/*--------------------------------------------PC PARA VISUALIZAR PERSONAL -------------------------------------------------*/
DROP PROCEDURE IF EXISTS SP_VISUALIZAR_PERSONAL;
DELIMITER //
CREATE PROCEDURE SP_VISUALIZAR_PERSONAL(
IN P_CEDULA_PERSONAL INT
)
BEGIN
DECLARE VALIDAR_CEDULA INT;
DECLARE MSJ VARCHAR(50);
SET VALIDAR_CEDULA = (SELECT F_CEDULA_PERSONAL_F(P_CEDULA_PERSONAL));
	START TRANSACTION;
    IF  VALIDAR_CEDULA IS NULL THEN
		SELECT CEDULA_PERSONAL, NOMBRE_PERSONAL, APELLIDO_PERSONAL, FECHA_NACIMIENTO, EDAD_PERSONAL, TELEFONO_PERSONAL, ROL
		FROM PERSONAL;
        COMMIT;
	ELSE
		SELECT CEDULA_PERSONAL, NOMBRE_PERSONAL, APELLIDO_PERSONAL, FECHA_NACIMIENTO, EDAD_PERSONAL, TELEFONO_PERSONAL, ROL
		FROM PERSONAL WHERE CEDULA_PERSONAL = P_CEDULA_PERSONAL;
		COMMIT;
	END IF;
END //
DELIMITER ;
-- BUSCADOR DE CLIENTES VISUALIZAR TODOS O UN SOLO CLIENTE ESPECIFICO
CALL SP_VISUALIZAR_PERSONAL(TRIM(1));