/*--------------------------------------------------CREACION DE TABLA TRATAMIENTO--------------------------------------------------------------*/
-- CREAMOS LA TABLA TRATAMIENTO
CREATE TABLE TIPO_TRATAMIENTO (
    ID_NOMBRE_TRATAMIENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_TRATAMIENTO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_NOMBRE_TRATAMIENTO),
    CONSTRAINT UN_TRATAMIENTO UNIQUE (NOMBRE_TRATAMIENTO)
);

/*--------------------------------------------------PROCEDIMIENTO CREAR TRATAMIENTO--------------------------------------------------------------*/
DROP PROCEDURE SP_CREAR_TIPO_TRATAMIENTO;
DELIMITER //
CREATE PROCEDURE SP_CREAR_TIPO_TRATAMIENTO (
IN TNOMBRE_TRATAMIENTO VARCHAR(100)
)
BEGIN 
START TRANSACTION;
	INSERT INTO TIPO_TRATAMIENTO (NOMBRE_TRATAMIENTO) VALUES (TRIM(TNOMBRE_TRATAMIENTO));
COMMIT;
END //
DELIMITER ;
CALL SP_CREAR_TIPO_TRATAMIENTO("TRATAMIENTO FACIAL");

/*---------------------------------------------FUNCION PARA IDENTIFICAR TRATAMIENTO-------------------------------------------------------------*/
DROP FUNCTION F_VER_TRATAMIENTO;
DELIMITER //
CREATE FUNCTION F_VER_TRATAMIENTO(TID_TRATAMIENTO INT)
RETURNS INT DETERMINISTIC 
BEGIN
    RETURN (SELECT ID_NOMBRE_TRATAMIENTO FROM TIPO_TRATAMIENTO WHERE ID_NOMBRE_TRATAMIENTO =  TID_TRATAMIENTO);
END //
DELIMITER ;
SELECT F_VER_TRATAMIENTO(1);
/*---------------------------------------------PROCEDIMIENTO VER TRATAMIENTO--------------------------------------------------------------*/
DROP PROCEDURE SP_VER_TIPO_TRATAMIENTO;
DELIMITER //
CREATE PROCEDURE SP_VER_TIPO_TRATAMIENTO (
IN T_ID INT
)
BEGIN 
DECLARE ID_TRATAMIENTO INT;
SET ID_TRATAMIENTO = (SELECT F_VER_TRATAMIENTO(T_ID));
START TRANSACTION;
	IF ID_TRATAMIENTO IS NULL THEN
        SELECT * FROM TIPO_TRATAMIENTO ORDER BY ID_NOMBRE_TRATAMIENTO ASC;
        COMMIT;
	ELSE
		SELECT * FROM  TIPO_TRATAMIENTO
        WHERE ID_NOMBRE_TRATAMIENTO = T_ID;
        COMMIT;
	END IF;
END //
DELIMITER ;
CALL SP_VER_TIPO_TRATAMIENTO(NULL);