CREATE DATABASE FISHIO;
USE FISHIO;
/*--------------------------------------------------TABLA CLIENTES  ---------------------------------------------------------------*/
CREATE TABLE CLIENTES (
    CEDULA_CLIENTE INT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(100) NOT NULL DEFAULT 'NOMBRE',
    APELLIDO_CLIENTE VARCHAR(100) NOT NULL DEFAULT 'APELLIDO',
    FECHA_NACIMIENTO DATE NOT NULL,
    EDAD_CLIENTE INT NOT NULL,
    TELEFONO_CLIENTE INT NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    DIRECCION TEXT NOT NULL,
    CLAVE VARCHAR(100) NOT NULL DEFAULT 'FISHIO2024',
    ROL VARCHAR(50) DEFAULT 'USUARIO',
    FOTO VARCHAR(250) DEFAULT NULL,
    PRIMARY KEY (CEDULA_CLIENTE),
    CONSTRAINT UK_TELEFONO UNIQUE (TELEFONO_CLIENTE),
    CONSTRAINT UK_CORREO UNIQUE (CORREO)
);
SELECT * FROM CLIENTES;
SET SQL_SAFE_UPDATES = 0;
DELETE FROM CLIENTES;
/*--------------------------------------------------PROCEDURE CREAR USUARIO---------------------------------------------------------------*/
DROP PROCEDURE IF EXISTS SP_CREAR_CLIENTE;
DELIMITER //
CREATE PROCEDURE SP_CREAR_CLIENTE(
IN P_CEDULA_CLIENTE INT,
IN P_NOMBRE_CLIENTE VARCHAR(100),
IN P_APELLIDO_CLIENTE VARCHAR(100),
IN P_FECHA_NACIMIENTO DATE,
IN P_EDAD_CLIENTE INT,
IN P_TELEFONO_CLIENTE int,
IN P_CORREO VARCHAR(100),
IN P_DIRECCION TEXT,
IN P_CLAVE VARCHAR(50)
)
BEGIN
DECLARE MSJ VARCHAR(50);
	START TRANSACTION;
IF LENGTH(P_CLAVE) <= 0 THEN
	SET MSJ = ("LA CLAVE DEBE TENER AL MENOS UN CARACTER");
	SELECT MSJ;
	ROLLBACK;
ELSE
	INSERT INTO CLIENTES (CEDULA_CLIENTE, NOMBRE_CLIENTE,APELLIDO_CLIENTE,FECHA_NACIMIENTO,EDAD_CLIENTE,TELEFONO_CLIENTE,CORREO,DIRECCION,CLAVE)
	VALUES (TRIM(P_CEDULA_CLIENTE), 
			TRIM(P_NOMBRE_CLIENTE), 
            TRIM(P_APELLIDO_CLIENTE),
            TRIM(P_FECHA_NACIMIENTO),
            TRIM(P_EDAD_CLIENTE),
            TRIM(P_TELEFONO_CLIENTE),
            TRIM(P_CORREO),
            TRIM(P_DIRECCION),
            TRIM(P_CLAVE));
	COMMIT;
END IF;
END //
DELIMITER ;
CALL SP_CREAR_CLIENTE(1312559824, 'Stalin','Valarezo','1996-08-01',Timestampdiff(YEAR , '1996-08-01', NOW()),'0979853522','stam@gmail.com','Los Esteros','12345');
/*--------------------------------------------------VISUALIZAR USUARIO CON CÉDULA---------------------------------------------------------------*/
DROP PROCEDURE IF EXISTS SP_VISUALIZAR_CLIENTE;
DELIMITER //
CREATE PROCEDURE SP_VISUALIZAR_CLIENTE(
IN P_CEDULA_CLIENTE INT
)
BEGIN
DECLARE VALIDAR_CEDULA INT;
DECLARE MSJ VARCHAR(50);
SET VALIDAR_CEDULA = (SELECT FUN_OBTENER_CEDULA_CLIENTE(P_CEDULA_CLIENTE));
	START TRANSACTION;
    IF  VALIDAR_CEDULA IS NULL THEN
		SELECT CEDULA_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, FECHA_NACIMIENTO, EDAD_CLIENTE, TELEFONO_CLIENTE, CORREO, DIRECCION
		FROM CLIENTES;
        COMMIT;
	ELSE
		SELECT CEDULA_CLIENTE, NOMBRE_CLIENTE, APELLIDO_CLIENTE, FECHA_NACIMIENTO, EDAD_CLIENTE, TELEFONO_CLIENTE, CORREO, DIRECCION
		FROM CLIENTES WHERE CEDULA_CLIENTE = P_CEDULA_CLIENTE;
	COMMIT;
	END IF;
END //
DELIMITER ;
-- BUSCADOR DE CLIENTES VISUALIZAR TODOS O UN SOLO CLIENTE ESPECIFICO
CALL SP_VISUALIZAR_CLIENTE(TRIM(1));
SELECT * FROM CLIENTES;
/*--------------------------------------------------ACTUALIZAR CLAVE USUARIO---------------------------------------------------------------*/
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_CLAVE_CLIENTE;
DELIMITER //
CREATE PROCEDURE SP_ACTUALIZAR_CLAVE_CLIENTE(
IN P_CEDULA_CLIENTE INT,
IN P_CLAVE INT
)
BEGIN
DECLARE VALIDAR_CEDULA INT;
DECLARE MSJ VARCHAR(50);
-- DECLARE LON INT;
SET VALIDAR_CEDULA = (SELECT FUN_OBTENER_CEDULA_CLIENTE(P_CEDULA_CLIENTE));
SET MSJ = 'CEDULA NO EXISTENTE';
-- SET LON = (SELECT FUN_LONGITUD_CEDULA_CLIENTE(P_CEDULA_CLIENTE));
START TRANSACTION;
	IF VALIDAR_CEDULA IS NOT NULL /*AND LON = 10*/ THEN 
			UPDATE CLIENTES SET CLAVE = P_CLAVE WHERE CEDULA_CLIENTE = P_CEDULA_CLIENTE;
			COMMIT;
		ELSE SELECT MSJ;
			ROLLBACK;
	END IF;
-- ROLLBACK;
END //
DELIMITER ;
CALL SP_ACTUALIZAR_CLAVE_CLIENTE(1312559824, '77777');
/*--------------------------------------------------FUNCION PARA OBTENER CEDULA USUARIO---------------------------------------------------------------*/
DROP FUNCTION  IF EXISTS FUN_OBTENER_CEDULA_CLIENTE;
DELIMITER //
CREATE FUNCTION FUN_OBTENER_CEDULA_CLIENTE(CEDULA INT)
RETURNS INT DETERMINISTIC
BEGIN
	RETURN (SELECT CEDULA_CLIENTE FROM CLIENTES WHERE CEDULA_CLIENTE = CEDULA);
END //
DELIMITER ;
SELECT FUN_OBTENER_CEDULA_CLIENTE(1312559824);

/*--------------------------------------------------FUNCION PARA OBTENER CEDULA LONGITUD---------------------------------------------------------------*/
/*DROP FUNCTION  IF EXISTS FUN_LONGITUD_CEDULA_CLIENTE
DELIMITER //
CREATE FUNCTION FUN_LONGITUD_CEDULA_CLIENTE(CEDULA INT)
RETURNS INT DETERMINISTIC
BEGIN
	RETURN (SELECT LENGTH(CEDULA_CLIENTE) FROM CLIENTES WHERE CEDULA_CLIENTE = CEDULA);
END //
DELIMITER ;
SELECT FUN_LONGITUD_CEDULA_CLIENTE(1312559824);*/